---
title: "How I Accidentally Started an Open Scholarship Community"
# format: revealjs
author:
  - name: Neil Shephard
    orcid: 0000-0001-8301-6857
    email: n.shephard@sheffield.ac.uk
    affiliations: The University of Sheffield
from: markdown+emoji
format:
  clean-revealjs:
    incremental: false
    slide-number: true
    show-slide-number: speaker
    auto-stretch: false
    chalkboard: true
    # embed-resources: true
    # standalone: true
revealjs-plugins:
  - confetti
footer: "**Slides** : [**ns-rse.github.io/open-research-conversation-2023-11**](https://ns-rse.github.io/open-research-conversation-2023-11)"
project:
  preview:
    port: 7864
    host: localhost
    watch-inputs: true
---

## Scan This!

{{< qrcode https://ns-rse.github.io/open-research-conversation-2023-11 qr1 width=400 height=400 >}}

[ns-rse.github.io/open-research-conversation-2023-11](https://ns-rse.github.io/open-research-conversation-2023-11)

## Background

+ Genetic Epidemiologist 2000-2008
+ Cancer Registry Statistician 2008-2009
+ Medical Statistician (Clinical Trials) 2009-2018
+ Data Scientist 2018-2022
+ Research Software Engineer 2022-Present

::: {.notes}
Good afternoon, my name is Neil Shephard and I'm a Research Software Engineer in the Department of Computer Science at
the University of Sheffield.

I've not always been a Research Software Engineer though, and have had a varied career spending time as a Genetic
Epidemiologist, then working at a Cancer Registry before nine years as a Medical Statistician in Clinical Trials and a
stint as a Data Scientist before ending up here.

What relevance does my career have? Well early on in my first job I discovered literate programming a method of writing
code for analysis and papers that made work reproducible and in realising that there is a different way of working from
the traditional and pervasive word processor and spreadsheets and that it was not only more efficient, but also meant
that it was easier to work in a reproducible and open manner which engendered a passion for Open Research that persists
today.

Now that I've explained very briefly how I came to be interested in Open Research I'm going to tell you a bit about how
I accidentally started the Open Scholarship Community Sheffield.
:::

## Communities


::: {.notes}
Speaker Notes can be added to each slide. **Formatting** can be used here too.
:::

## OSC Incubator Programme


:::: {.columns}

::: {.column width="50%"}
**ToDo** (code)

```markdown
+ Learn Markdown
+ Create Quarto Slides
+ Publish on GitHub
```

:::

::: {.column width="50%"}
**ToDo** (Rendered)

+ Learn Markdown
+ Create Quarto Slides
+ Publish on GitHub

:::
::::

::: {.notes}
Slides can have columns and we can create unordered lists.
:::
